---

- name: Sysconfig nomad file
  template: src=nomad.sysconfig.j2 dest={{ nomad_sysconfig }}
  notify: restart nomad service

- name: Main nomad configuration file
  template: src=nomad.hcl.j2 dest=/etc/nomad.d/nomad.hcl
  notify: restart nomad service

- name: Creates systemd service files
  when: nomad_http_proxy != None or nomad_https_proxy != None or nomad_http_no_proxy != None
  block:
    - name: Creates /etc/systemd/system/nomad.service.d
      file: path=/etc/systemd/system/nomad.service.d state=directory

    - name: Creates http proxy configuration file
      template: src=http-options.conf.j2 dest=/etc/systemd/system/nomad.service.d/http-options.conf
      notify:
        - reload systemd
        - restart nomad service
        #- restart nomad resource

- name: Removes proxy configuration
  file: path=/etc/systemd/systemd/nomad.service.d/http-options.conf state=absent
  notify:
    - reload systemd
    - restart nomad service
    #- restart nomad resource
  when:
    - nomad_http_proxy == None
    - nomad_https_proxy == None
    - nomad_http_no_proxy == None

- name: Telegraf configuration
  when:
    - configure_telegraf == true
  notify: restart telegraf
  template: src=nomad.telegraf.conf.j2 dest=/etc/telegraf/telegraf.d/nomad.conf

- name: Consul monitoring
  when:
    - configure_nomad_ui | lower == 'true'
  template: src=service.consul.json.j2 dest={{ nomad_consul_services_path }}/{{ item.service.name }}.json
  with_items: "{{ nomad_nomad_ui }}"
  notify: reload consul

- name: Autostart nomad
  service: name=nomad state=started enabled={{ nomad_service_enabled }}
