---

- name: Pre-Install | Check Openstack credentials
  fail: msg="Openstack credencials must be present"
  when: (lookup('env', 'OS_USERNAME') is undefined
    or lookup('env', 'OS_PASSWORD') is undefined
    or lookup('env', 'OS_AUTH_URL') is undefined
    or lookup('env', 'OS_PROJECT_ID') is undefined
    or lookup('env', 'OS_USER_DOMAIN_NAME') is undefined)
    and nomad_acl_store_swift | lower == 'true'
    and nomad_enable_acl | lower == 'true'

- name: Pre-Install | Check vault token
  fail: msg="Vault is enabled but no token given"
  when:
    - nomad_server_mode | lower == 'true'
    - nomad_enable_vault | lower == 'true'
    - nomad_vault_token == None or nomad_vault_token | length == 0

- name: Pre-Install | Check vault url
  fail: msg="Vault is enabled but no url given"
  when:
    - nomad_enable_vault | lower == 'true'
    - nomad_vault_url == None or nomad_vault_url | length == 0

- name: Pre-Install | Check nomad_bootstrap_expect
  fail: msg="nomad_bootstrap_expect must be positive"
  when:
    - nomad_server_mode | lower == 'true'
    - nomad_bootstrap_expect is defined
    - nomad_bootstrap_expect | int == 0
    - play_hosts | length == 0

- name: Pre-Install | Set local facts
  set_fact:
    configure_nomad_ui: false
    configure_telegraf: false
    use_consul: false

- name: Pre-Install | Check running services
  service_facts:

- name: Pre-Install | Activate nomad ui
  when:
    - nomad_config_nomad_ui | lower == 'true'
    - nomad_server_mode | lower == 'true'
  set_fact: configure_nomad_ui=true

- name: Pre-Install | Set local facts (configure_telegraf = true)
  when:
    - ansible_facts.services | map('quote') | join(',') | regex_search('telegraf')
    - nomad_config_telegraf | lower == 'true'
  set_fact:
    configure_telegraf: true

- name: Pre-Install | Set local facts (use_consul = true)
  when:
    - ansible_facts.services | map('quote') | join(',') | regex_search('consul')
  set_fact:
    use_consul: true

- name: Pre-Install | Declare APT repo
  when: ansible_pkg_mgr | lower == 'apt'
  block:
  - name: Pre-Install | Add APT key (with proxy)
    when:
    - nomad_http_proxy != None
    environment:
      http_proxy: '{{ nomad_http_proxy }}'
      https_proxy: '{{ nomad_https_proxy }}'
      no_proxy: '{{ nomad_http_no_proxy }}'
    apt_key:
      url: '{{ nomad_apt_key }}'
      state: present

  - name: Pre-Install | Add APT key (with proxy)
    when:
    - nomad_http_proxy == None
    apt_key:
      url: '{{ nomad_apt_key }}'
      state: present

  - name: Pre-Install | Add APT repo
    apt_repository:
      repo: '{{ nomad_apt_repo }}'
      state: present

- name: Pre-Install | Declare RPM repo
  when: ansible_pkg_mgr | lower == 'dnf' or ansible_pkg_mgr | lower == 'rpm'
  block:
  - name: Pre-Install | Add RPM repo
    yum_repository:
      name: hashicorp
      description: Official Hashicorp RPM repository
      baseurl: '{{ nomad_rpm_repo }}'
      gpgkey: '{{ nomad_rpm_key }}'
      state: present
      proxy: "{{ nomad_http_proxy }}"
