---

- name: reload firewalld
  command: firewall-cmd --reload

- name: restart nomad service
  service: name=nomad state=restarted enabled={{ nomad_service_enabled }}

- name: reload systemd
  systemd: daemon_reload=yes

- name: reload consul
  command: "{{ consul_bin }} reload"

- name: restart telegraf
  service: name=telegraf state=restarted
